services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=cloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  backend:
    build:
      context: ./backend
      network: host
    restart: always
    volumes:
      - ./user_files:/app/user_files
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      network: host
      args:
        - VITE_KEY_REDUX=${VITE_KEY_REDUX}
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: